# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.models.post_pix_qrcode_read400_response import PostPixQrcodeRead400Response

class TestPostPixQrcodeRead400Response(unittest.TestCase):
    """PostPixQrcodeRead400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPixQrcodeRead400Response:
        """Test PostPixQrcodeRead400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPixQrcodeRead400Response`
        """
        model = PostPixQrcodeRead400Response()
        if include_optional:
            return PostPixQrcodeRead400Response(
                error = 'INVALID_QR_CODE',
                message = 'The provided EMV payload is invalid or malformed.'
            )
        else:
            return PostPixQrcodeRead400Response(
        )
        """

    def testPostPixQrcodeRead400Response(self):
        """Test PostPixQrcodeRead400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
