# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install @payzu/pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.models.get_user_transaction_by_id200_response import GetUserTransactionById200Response

class TestGetUserTransactionById200Response(unittest.TestCase):
    """GetUserTransactionById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserTransactionById200Response:
        """Test GetUserTransactionById200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserTransactionById200Response`
        """
        model = GetUserTransactionById200Response()
        if include_optional:
            return GetUserTransactionById200Response(
                id = '',
                status = '',
                amount = 1.337,
                type = '',
                callback_url = '',
                qr_code_text = '',
                qr_code_base64 = '',
                qr_code_url = '',
                generated_name = '',
                generated_document = '',
                generated_email = '',
                payer_name = '',
                payer_document = '',
                payer_institution_ispb = '',
                payer_institution_name = '',
                payer_account_number = '',
                service_fee_charged = 1.337,
                withdraw_pix_key = '',
                withdraw_pix_type = '',
                receiver_name = '',
                receiver_document = '',
                receiver_institution_ispb = '',
                receiver_institution_name = '',
                receiver_account_number = '',
                end_to_end_id = '',
                created_at = '',
                updated_at = '',
                paid_at = '',
                client_reference = '',
                refund_end_to_end_id = '',
                refund_amount = '',
                refund_status = '',
                refund_reason = '',
                refund_description = '',
                refunded_at = '',
                cancellation_reason = '',
                infraction = payzu_pix.models.transaction_infraction.Transaction_infraction(
                    id = '', 
                    protocol = '', 
                    status = 'WAITING_PSP', 
                    type = 'REFUND_REQUEST', 
                    report_details = '', 
                    reported_by = 'DEBITED_PARTICIPANT', 
                    analysis_result = '', 
                    analysis_details = '', 
                    reported_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                virtual_account = '',
                infractions = [
                    payzu_pix.models.get_user_transaction_by_id_200_response_all_of_infractions_inner.get_user_transaction_by_id_200_response_allOf_infractions_inner(
                        id = '', 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                callback_logs = [
                    payzu_pix.models.get_user_transaction_by_id_200_response_all_of_callback_logs_inner.get_user_transaction_by_id_200_response_allOf_callbackLogs_inner(
                        id = '', 
                        url = '', 
                        status = 56, 
                        response_time = 1.337, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetUserTransactionById200Response(
        )
        """

    def testGetUserTransactionById200Response(self):
        """Test GetUserTransactionById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
