# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.models.get_user_balance200_response import GetUserBalance200Response

class TestGetUserBalance200Response(unittest.TestCase):
    """GetUserBalance200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserBalance200Response:
        """Test GetUserBalance200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserBalance200Response`
        """
        model = GetUserBalance200Response()
        if include_optional:
            return GetUserBalance200Response(
                balance_available = 1.337,
                balance_blocked = 1.337
            )
        else:
            return GetUserBalance200Response(
        )
        """

    def testGetUserBalance200Response(self):
        """Test GetUserBalance200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
