# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.api.reports_api import ReportsApi


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportsApi()

    def tearDown(self) -> None:
        pass

    def test_download_user_report(self) -> None:
        """Test case for download_user_report

        Download report
        """
        pass

    def test_get_user_report(self) -> None:
        """Test case for get_user_report

        Consultar status do relatório
        """
        pass

    def test_get_user_transaction_by_id(self) -> None:
        """Test case for get_user_transaction_by_id

        List transaction details
        """
        pass

    def test_get_user_transactions(self) -> None:
        """Test case for get_user_transactions

        List Transactions
        """
        pass

    def test_list_user_reports(self) -> None:
        """Test case for list_user_reports

        List report jobs
        """
        pass

    def test_post_user_report(self) -> None:
        """Test case for post_user_report

        Generate transactions report
        """
        pass


if __name__ == '__main__':
    unittest.main()
