<?php
/**
 * PostPixRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayZu Pix API
 *
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PostPixRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostPixRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'post_pix_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'amount' => 'float',
        'callback_url' => 'string',
        'generated_name' => 'string',
        'generated_email' => 'string',
        'generated_document' => 'string',
        'expires_in' => 'float',
        'client_reference' => 'string',
        'virtual_account' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'amount' => null,
        'callback_url' => null,
        'generated_name' => null,
        'generated_email' => null,
        'generated_document' => null,
        'expires_in' => null,
        'client_reference' => null,
        'virtual_account' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'amount' => false,
        'callback_url' => false,
        'generated_name' => false,
        'generated_email' => false,
        'generated_document' => false,
        'expires_in' => false,
        'client_reference' => false,
        'virtual_account' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
        'callback_url' => 'callbackUrl',
        'generated_name' => 'generatedName',
        'generated_email' => 'generatedEmail',
        'generated_document' => 'generatedDocument',
        'expires_in' => 'expiresIn',
        'client_reference' => 'clientReference',
        'virtual_account' => 'virtualAccount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
        'callback_url' => 'setCallbackUrl',
        'generated_name' => 'setGeneratedName',
        'generated_email' => 'setGeneratedEmail',
        'generated_document' => 'setGeneratedDocument',
        'expires_in' => 'setExpiresIn',
        'client_reference' => 'setClientReference',
        'virtual_account' => 'setVirtualAccount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
        'callback_url' => 'getCallbackUrl',
        'generated_name' => 'getGeneratedName',
        'generated_email' => 'getGeneratedEmail',
        'generated_document' => 'getGeneratedDocument',
        'expires_in' => 'getExpiresIn',
        'client_reference' => 'getClientReference',
        'virtual_account' => 'getVirtualAccount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('generated_name', $data ?? [], null);
        $this->setIfExists('generated_email', $data ?? [], null);
        $this->setIfExists('generated_document', $data ?? [], null);
        $this->setIfExists('expires_in', $data ?? [], null);
        $this->setIfExists('client_reference', $data ?? [], null);
        $this->setIfExists('virtual_account', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] < 1)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['expires_in']) && ($this->container['expires_in'] > 172000)) {
            $invalidProperties[] = "invalid value for 'expires_in', must be smaller than or equal to 172000.";
        }

        if (!is_null($this->container['client_reference']) && (mb_strlen($this->container['client_reference']) > 64)) {
            $invalidProperties[] = "invalid value for 'client_reference', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['virtual_account']) && (mb_strlen($this->container['virtual_account']) > 50)) {
            $invalidProperties[] = "invalid value for 'virtual_account', the character length must be smaller than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount Amount in BRL. Must be >= 1.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount < 1)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PostPixRequest., must be bigger than or equal to 1.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url URL to receive `transaction updated` webhooks.
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }
        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets generated_name
     *
     * @return string|null
     */
    public function getGeneratedName()
    {
        return $this->container['generated_name'];
    }

    /**
     * Sets generated_name
     *
     * @param string|null $generated_name Payer full name. Letters and spaces only.
     *
     * @return self
     */
    public function setGeneratedName($generated_name)
    {
        if (is_null($generated_name)) {
            throw new \InvalidArgumentException('non-nullable generated_name cannot be null');
        }
        $this->container['generated_name'] = $generated_name;

        return $this;
    }

    /**
     * Gets generated_email
     *
     * @return string|null
     */
    public function getGeneratedEmail()
    {
        return $this->container['generated_email'];
    }

    /**
     * Sets generated_email
     *
     * @param string|null $generated_email Payer email (optional).
     *
     * @return self
     */
    public function setGeneratedEmail($generated_email)
    {
        if (is_null($generated_email)) {
            throw new \InvalidArgumentException('non-nullable generated_email cannot be null');
        }
        $this->container['generated_email'] = $generated_email;

        return $this;
    }

    /**
     * Gets generated_document
     *
     * @return string|null
     */
    public function getGeneratedDocument()
    {
        return $this->container['generated_document'];
    }

    /**
     * Sets generated_document
     *
     * @param string|null $generated_document Payer CPF (11 digits) or CNPJ (14 digits), no punctuation.
     *
     * @return self
     */
    public function setGeneratedDocument($generated_document)
    {
        if (is_null($generated_document)) {
            throw new \InvalidArgumentException('non-nullable generated_document cannot be null');
        }
        $this->container['generated_document'] = $generated_document;

        return $this;
    }

    /**
     * Gets expires_in
     *
     * @return float|null
     */
    public function getExpiresIn()
    {
        return $this->container['expires_in'];
    }

    /**
     * Sets expires_in
     *
     * @param float|null $expires_in Seconds until the QR Code expires. Default: 600.
     *
     * @return self
     */
    public function setExpiresIn($expires_in)
    {
        if (is_null($expires_in)) {
            throw new \InvalidArgumentException('non-nullable expires_in cannot be null');
        }

        if (($expires_in > 172000)) {
            throw new \InvalidArgumentException('invalid value for $expires_in when calling PostPixRequest., must be smaller than or equal to 172000.');
        }

        $this->container['expires_in'] = $expires_in;

        return $this;
    }

    /**
     * Gets client_reference
     *
     * @return string|null
     */
    public function getClientReference()
    {
        return $this->container['client_reference'];
    }

    /**
     * Sets client_reference
     *
     * @param string|null $client_reference External reference (order, invoice, etc.).
     *
     * @return self
     */
    public function setClientReference($client_reference)
    {
        if (is_null($client_reference)) {
            throw new \InvalidArgumentException('non-nullable client_reference cannot be null');
        }
        if ((mb_strlen($client_reference) > 64)) {
            throw new \InvalidArgumentException('invalid length for $client_reference when calling PostPixRequest., must be smaller than or equal to 64.');
        }

        $this->container['client_reference'] = $client_reference;

        return $this;
    }

    /**
     * Gets virtual_account
     *
     * @return string|null
     */
    public function getVirtualAccount()
    {
        return $this->container['virtual_account'];
    }

    /**
     * Sets virtual_account
     *
     * @param string|null $virtual_account Subconta virtual (até 50 caracteres) para correlacionar lojas, filiais, marketplaces. Volta no callback.
     *
     * @return self
     */
    public function setVirtualAccount($virtual_account)
    {
        if (is_null($virtual_account)) {
            throw new \InvalidArgumentException('non-nullable virtual_account cannot be null');
        }
        if ((mb_strlen($virtual_account) > 50)) {
            throw new \InvalidArgumentException('invalid length for $virtual_account when calling PostPixRequest., must be smaller than or equal to 50.');
        }

        $this->container['virtual_account'] = $virtual_account;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


