# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install @payzu/pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from payzu_pix.models.get_user_transaction_by_id200_response_all_of_callback_logs_inner import GetUserTransactionById200ResponseAllOfCallbackLogsInner
from payzu_pix.models.get_user_transaction_by_id200_response_all_of_infractions_inner import GetUserTransactionById200ResponseAllOfInfractionsInner
from payzu_pix.models.transaction_infraction import TransactionInfraction
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetUserTransactionById200Response(BaseModel):
    """
    GetUserTransactionById200Response
    """ # noqa: E501
    id: Optional[StrictStr] = None
    status: Optional[StrictStr] = Field(default=None, description="PENDING, COMPLETED, CANCELED, WAITING_FOR_REFUND, REFUNDED, EXPIRED, ERROR")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    type: Optional[StrictStr] = Field(default=None, description="DEPOSIT or WITHDRAW")
    callback_url: Optional[StrictStr] = Field(default=None, alias="callbackUrl")
    qr_code_text: Optional[StrictStr] = Field(default=None, alias="qrCodeText")
    qr_code_base64: Optional[StrictStr] = Field(default=None, alias="qrCodeBase64")
    qr_code_url: Optional[StrictStr] = Field(default=None, alias="qrCodeUrl")
    generated_name: Optional[StrictStr] = Field(default=None, alias="generatedName")
    generated_document: Optional[StrictStr] = Field(default=None, alias="generatedDocument")
    generated_email: Optional[StrictStr] = Field(default=None, alias="generatedEmail")
    payer_name: Optional[StrictStr] = Field(default=None, alias="payerName")
    payer_document: Optional[StrictStr] = Field(default=None, alias="payerDocument")
    payer_institution_ispb: Optional[StrictStr] = Field(default=None, alias="payerInstitutionIspb")
    payer_institution_name: Optional[StrictStr] = Field(default=None, alias="payerInstitutionName")
    payer_account_number: Optional[StrictStr] = Field(default=None, description="Payer's PayZu account number (6 digits). Present only on internal-transfer transactions.", alias="payerAccountNumber")
    service_fee_charged: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="serviceFeeCharged")
    withdraw_pix_key: Optional[StrictStr] = Field(default=None, alias="withdrawPixKey")
    withdraw_pix_type: Optional[StrictStr] = Field(default=None, alias="withdrawPixType")
    receiver_name: Optional[StrictStr] = Field(default=None, alias="receiverName")
    receiver_document: Optional[StrictStr] = Field(default=None, alias="receiverDocument")
    receiver_institution_ispb: Optional[StrictStr] = Field(default=None, alias="receiverInstitutionIspb")
    receiver_institution_name: Optional[StrictStr] = Field(default=None, alias="receiverInstitutionName")
    receiver_account_number: Optional[StrictStr] = Field(default=None, description="Receiver's PayZu account number (6 digits). Present only on internal-transfer transactions.", alias="receiverAccountNumber")
    end_to_end_id: Optional[StrictStr] = Field(default=None, alias="endToEndId")
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    updated_at: Optional[StrictStr] = Field(default=None, alias="updatedAt")
    paid_at: Optional[StrictStr] = Field(default=None, alias="paidAt")
    client_reference: Optional[StrictStr] = Field(default=None, alias="clientReference")
    refund_end_to_end_id: Optional[StrictStr] = Field(default=None, description="End-to-end ID of the refund transaction", alias="refundEndToEndId")
    refund_amount: Optional[StrictStr] = Field(default=None, description="Amount refunded", alias="refundAmount")
    refund_status: Optional[StrictStr] = Field(default=None, description="Status of the refund (PENDING, COMPLETED, CANCELED, WAITING_FOR_REFUND, REFUNDED, EXPIRED, ERROR)", alias="refundStatus")
    refund_reason: Optional[StrictStr] = Field(default=None, description="Reason for the refund", alias="refundReason")
    refund_description: Optional[StrictStr] = Field(default=None, description="Description of the refund", alias="refundDescription")
    refunded_at: Optional[StrictStr] = Field(default=None, description="Date and time when the refund was processed", alias="refundedAt")
    cancellation_reason: Optional[StrictStr] = Field(default=None, description="Reason for cancellation (if cancelled)", alias="cancellationReason")
    infraction: Optional[TransactionInfraction] = None
    virtual_account: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Subconta virtual informada na criação.", alias="virtualAccount")
    infractions: Optional[List[GetUserTransactionById200ResponseAllOfInfractionsInner]] = Field(default=None, description="Histórico completo de infrações desta transação.")
    callback_logs: Optional[List[GetUserTransactionById200ResponseAllOfCallbackLogsInner]] = Field(default=None, description="Webhook delivery attempts for this transaction (most recent first)", alias="callbackLogs")
    __properties: ClassVar[List[str]] = ["id", "status", "amount", "type", "callbackUrl", "qrCodeText", "qrCodeBase64", "qrCodeUrl", "generatedName", "generatedDocument", "generatedEmail", "payerName", "payerDocument", "payerInstitutionIspb", "payerInstitutionName", "payerAccountNumber", "serviceFeeCharged", "withdrawPixKey", "withdrawPixType", "receiverName", "receiverDocument", "receiverInstitutionIspb", "receiverInstitutionName", "receiverAccountNumber", "endToEndId", "createdAt", "updatedAt", "paidAt", "clientReference", "refundEndToEndId", "refundAmount", "refundStatus", "refundReason", "refundDescription", "refundedAt", "cancellationReason", "infraction", "virtualAccount", "infractions", "callbackLogs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUserTransactionById200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of infraction
        if self.infraction:
            _dict['infraction'] = self.infraction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in infractions (list)
        _items = []
        if self.infractions:
            for _item_infractions in self.infractions:
                if _item_infractions:
                    _items.append(_item_infractions.to_dict())
            _dict['infractions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in callback_logs (list)
        _items = []
        if self.callback_logs:
            for _item_callback_logs in self.callback_logs:
                if _item_callback_logs:
                    _items.append(_item_callback_logs.to_dict())
            _dict['callbackLogs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUserTransactionById200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "amount": obj.get("amount"),
            "type": obj.get("type"),
            "callbackUrl": obj.get("callbackUrl"),
            "qrCodeText": obj.get("qrCodeText"),
            "qrCodeBase64": obj.get("qrCodeBase64"),
            "qrCodeUrl": obj.get("qrCodeUrl"),
            "generatedName": obj.get("generatedName"),
            "generatedDocument": obj.get("generatedDocument"),
            "generatedEmail": obj.get("generatedEmail"),
            "payerName": obj.get("payerName"),
            "payerDocument": obj.get("payerDocument"),
            "payerInstitutionIspb": obj.get("payerInstitutionIspb"),
            "payerInstitutionName": obj.get("payerInstitutionName"),
            "payerAccountNumber": obj.get("payerAccountNumber"),
            "serviceFeeCharged": obj.get("serviceFeeCharged"),
            "withdrawPixKey": obj.get("withdrawPixKey"),
            "withdrawPixType": obj.get("withdrawPixType"),
            "receiverName": obj.get("receiverName"),
            "receiverDocument": obj.get("receiverDocument"),
            "receiverInstitutionIspb": obj.get("receiverInstitutionIspb"),
            "receiverInstitutionName": obj.get("receiverInstitutionName"),
            "receiverAccountNumber": obj.get("receiverAccountNumber"),
            "endToEndId": obj.get("endToEndId"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "paidAt": obj.get("paidAt"),
            "clientReference": obj.get("clientReference"),
            "refundEndToEndId": obj.get("refundEndToEndId"),
            "refundAmount": obj.get("refundAmount"),
            "refundStatus": obj.get("refundStatus"),
            "refundReason": obj.get("refundReason"),
            "refundDescription": obj.get("refundDescription"),
            "refundedAt": obj.get("refundedAt"),
            "cancellationReason": obj.get("cancellationReason"),
            "infraction": TransactionInfraction.from_dict(obj["infraction"]) if obj.get("infraction") is not None else None,
            "virtualAccount": obj.get("virtualAccount"),
            "infractions": [GetUserTransactionById200ResponseAllOfInfractionsInner.from_dict(_item) for _item in obj["infractions"]] if obj.get("infractions") is not None else None,
            "callbackLogs": [GetUserTransactionById200ResponseAllOfCallbackLogsInner.from_dict(_item) for _item in obj["callbackLogs"]] if obj.get("callbackLogs") is not None else None
        })
        return _obj


