<?php
/**
 * CallbacksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayZu Pix API
 *
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * CallbacksApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CallbacksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getUserCallbackById' => [
            'application/json',
        ],
        'getUserCallbacks' => [
            'application/json',
        ],
        'resendUserCallbackSingle' => [
            'application/json',
        ],
        'resendUserCallbacks' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUserCallbackById
     *
     * Get Callback
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Unique callback ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbackById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CallbackDetail|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getUserCallbackById($content_type, $id, string $contentType = self::contentTypes['getUserCallbackById'][0])
    {
        list($response) = $this->getUserCallbackByIdWithHttpInfo($content_type, $id, $contentType);
        return $response;
    }

    /**
     * Operation getUserCallbackByIdWithHttpInfo
     *
     * Get Callback
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Unique callback ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbackById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CallbackDetail|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserCallbackByIdWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getUserCallbackById'][0])
    {
        $request = $this->getUserCallbackByIdRequest($content_type, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CallbackDetail',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\CallbackDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CallbackDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUserCallbackByIdAsync
     *
     * Get Callback
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Unique callback ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbackById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCallbackByIdAsync($content_type, $id, string $contentType = self::contentTypes['getUserCallbackById'][0])
    {
        return $this->getUserCallbackByIdAsyncWithHttpInfo($content_type, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserCallbackByIdAsyncWithHttpInfo
     *
     * Get Callback
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Unique callback ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbackById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCallbackByIdAsyncWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getUserCallbackById'][0])
    {
        $returnType = '\OpenAPI\Client\Model\CallbackDetail';
        $request = $this->getUserCallbackByIdRequest($content_type, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserCallbackById'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Unique callback ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbackById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserCallbackByIdRequest($content_type, $id, string $contentType = self::contentTypes['getUserCallbackById'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getUserCallbackById'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getUserCallbackById'
            );
        }


        $resourcePath = '/user/callbacks/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUserCallbacks
     *
     * List Callbacks
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 10)
     * @param  string|null $sort_by sort_by (optional, default to 'createdAt')
     * @param  string|null $sort_direction sort_direction (optional, default to 'desc')
     * @param  string|null $id Filter by callback ID (optional)
     * @param  string|null $url Filter by callback URL (optional)
     * @param  int|null $status HTTP status code (optional)
     * @param  string|null $transaction_id transaction_id (optional)
     * @param  bool|null $has_error Filter callbacks that errored (optional)
     * @param  \DateTime|null $created_at_from created_at_from (optional)
     * @param  \DateTime|null $created_at_to created_at_to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbacks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CallbackListResponse|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getUserCallbacks($content_type, $page = 1, $limit = 10, $sort_by = 'createdAt', $sort_direction = 'desc', $id = null, $url = null, $status = null, $transaction_id = null, $has_error = null, $created_at_from = null, $created_at_to = null, string $contentType = self::contentTypes['getUserCallbacks'][0])
    {
        list($response) = $this->getUserCallbacksWithHttpInfo($content_type, $page, $limit, $sort_by, $sort_direction, $id, $url, $status, $transaction_id, $has_error, $created_at_from, $created_at_to, $contentType);
        return $response;
    }

    /**
     * Operation getUserCallbacksWithHttpInfo
     *
     * List Callbacks
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $sort_by (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $id Filter by callback ID (optional)
     * @param  string|null $url Filter by callback URL (optional)
     * @param  int|null $status HTTP status code (optional)
     * @param  string|null $transaction_id (optional)
     * @param  bool|null $has_error Filter callbacks that errored (optional)
     * @param  \DateTime|null $created_at_from (optional)
     * @param  \DateTime|null $created_at_to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbacks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CallbackListResponse|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserCallbacksWithHttpInfo($content_type, $page = 1, $limit = 10, $sort_by = 'createdAt', $sort_direction = 'desc', $id = null, $url = null, $status = null, $transaction_id = null, $has_error = null, $created_at_from = null, $created_at_to = null, string $contentType = self::contentTypes['getUserCallbacks'][0])
    {
        $request = $this->getUserCallbacksRequest($content_type, $page, $limit, $sort_by, $sort_direction, $id, $url, $status, $transaction_id, $has_error, $created_at_from, $created_at_to, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\CallbackListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\CallbackListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CallbackListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUserCallbacksAsync
     *
     * List Callbacks
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $sort_by (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $id Filter by callback ID (optional)
     * @param  string|null $url Filter by callback URL (optional)
     * @param  int|null $status HTTP status code (optional)
     * @param  string|null $transaction_id (optional)
     * @param  bool|null $has_error Filter callbacks that errored (optional)
     * @param  \DateTime|null $created_at_from (optional)
     * @param  \DateTime|null $created_at_to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCallbacksAsync($content_type, $page = 1, $limit = 10, $sort_by = 'createdAt', $sort_direction = 'desc', $id = null, $url = null, $status = null, $transaction_id = null, $has_error = null, $created_at_from = null, $created_at_to = null, string $contentType = self::contentTypes['getUserCallbacks'][0])
    {
        return $this->getUserCallbacksAsyncWithHttpInfo($content_type, $page, $limit, $sort_by, $sort_direction, $id, $url, $status, $transaction_id, $has_error, $created_at_from, $created_at_to, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserCallbacksAsyncWithHttpInfo
     *
     * List Callbacks
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $sort_by (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $id Filter by callback ID (optional)
     * @param  string|null $url Filter by callback URL (optional)
     * @param  int|null $status HTTP status code (optional)
     * @param  string|null $transaction_id (optional)
     * @param  bool|null $has_error Filter callbacks that errored (optional)
     * @param  \DateTime|null $created_at_from (optional)
     * @param  \DateTime|null $created_at_to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCallbacksAsyncWithHttpInfo($content_type, $page = 1, $limit = 10, $sort_by = 'createdAt', $sort_direction = 'desc', $id = null, $url = null, $status = null, $transaction_id = null, $has_error = null, $created_at_from = null, $created_at_to = null, string $contentType = self::contentTypes['getUserCallbacks'][0])
    {
        $returnType = '\OpenAPI\Client\Model\CallbackListResponse';
        $request = $this->getUserCallbacksRequest($content_type, $page, $limit, $sort_by, $sort_direction, $id, $url, $status, $transaction_id, $has_error, $created_at_from, $created_at_to, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserCallbacks'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $sort_by (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $id Filter by callback ID (optional)
     * @param  string|null $url Filter by callback URL (optional)
     * @param  int|null $status HTTP status code (optional)
     * @param  string|null $transaction_id (optional)
     * @param  bool|null $has_error Filter callbacks that errored (optional)
     * @param  \DateTime|null $created_at_from (optional)
     * @param  \DateTime|null $created_at_to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserCallbacksRequest($content_type, $page = 1, $limit = 10, $sort_by = 'createdAt', $sort_direction = 'desc', $id = null, $url = null, $status = null, $transaction_id = null, $has_error = null, $created_at_from = null, $created_at_to = null, string $contentType = self::contentTypes['getUserCallbacks'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getUserCallbacks'
            );
        }

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling CallbacksApi.getUserCallbacks, must be bigger than or equal to 1.');
        }
        
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CallbacksApi.getUserCallbacks, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CallbacksApi.getUserCallbacks, must be bigger than or equal to 1.');
        }
        










        $resourcePath = '/user/callbacks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sortBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sortDirection', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $url,
            'url', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transaction_id,
            'transactionId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $has_error,
            'hasError', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at_from,
            'createdAtFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at_to,
            'createdAtTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resendUserCallbackSingle
     *
     * Re-send callback (single)
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $transaction_id transaction_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbackSingle'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ResendUserCallbackSingle200Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function resendUserCallbackSingle($content_type, $transaction_id, string $contentType = self::contentTypes['resendUserCallbackSingle'][0])
    {
        list($response) = $this->resendUserCallbackSingleWithHttpInfo($content_type, $transaction_id, $contentType);
        return $response;
    }

    /**
     * Operation resendUserCallbackSingleWithHttpInfo
     *
     * Re-send callback (single)
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $transaction_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbackSingle'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ResendUserCallbackSingle200Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function resendUserCallbackSingleWithHttpInfo($content_type, $transaction_id, string $contentType = self::contentTypes['resendUserCallbackSingle'][0])
    {
        $request = $this->resendUserCallbackSingleRequest($content_type, $transaction_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResendUserCallbackSingle200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ResendUserCallbackSingle200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResendUserCallbackSingle200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resendUserCallbackSingleAsync
     *
     * Re-send callback (single)
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $transaction_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbackSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resendUserCallbackSingleAsync($content_type, $transaction_id, string $contentType = self::contentTypes['resendUserCallbackSingle'][0])
    {
        return $this->resendUserCallbackSingleAsyncWithHttpInfo($content_type, $transaction_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resendUserCallbackSingleAsyncWithHttpInfo
     *
     * Re-send callback (single)
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $transaction_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbackSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resendUserCallbackSingleAsyncWithHttpInfo($content_type, $transaction_id, string $contentType = self::contentTypes['resendUserCallbackSingle'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ResendUserCallbackSingle200Response';
        $request = $this->resendUserCallbackSingleRequest($content_type, $transaction_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resendUserCallbackSingle'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $transaction_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbackSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resendUserCallbackSingleRequest($content_type, $transaction_id, string $contentType = self::contentTypes['resendUserCallbackSingle'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling resendUserCallbackSingle'
            );
        }

        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null || (is_array($transaction_id) && count($transaction_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $transaction_id when calling resendUserCallbackSingle'
            );
        }


        $resourcePath = '/user/callbacks/resend/{transactionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($transaction_id !== null) {
            $resourcePath = str_replace(
                '{transactionId}',
                ObjectSerializer::toPathValue($transaction_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resendUserCallbacks
     *
     * Re-send callbacks (bulk)
     *
     * @param  \OpenAPI\Client\Model\ResendUserCallbacksRequest $resend_user_callbacks_request resend_user_callbacks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbacks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ResendUserCallbacks200Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function resendUserCallbacks($resend_user_callbacks_request, string $contentType = self::contentTypes['resendUserCallbacks'][0])
    {
        list($response) = $this->resendUserCallbacksWithHttpInfo($resend_user_callbacks_request, $contentType);
        return $response;
    }

    /**
     * Operation resendUserCallbacksWithHttpInfo
     *
     * Re-send callbacks (bulk)
     *
     * @param  \OpenAPI\Client\Model\ResendUserCallbacksRequest $resend_user_callbacks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbacks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ResendUserCallbacks200Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function resendUserCallbacksWithHttpInfo($resend_user_callbacks_request, string $contentType = self::contentTypes['resendUserCallbacks'][0])
    {
        $request = $this->resendUserCallbacksRequest($resend_user_callbacks_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ResendUserCallbacks200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ResendUserCallbacks200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResendUserCallbacks200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resendUserCallbacksAsync
     *
     * Re-send callbacks (bulk)
     *
     * @param  \OpenAPI\Client\Model\ResendUserCallbacksRequest $resend_user_callbacks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resendUserCallbacksAsync($resend_user_callbacks_request, string $contentType = self::contentTypes['resendUserCallbacks'][0])
    {
        return $this->resendUserCallbacksAsyncWithHttpInfo($resend_user_callbacks_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resendUserCallbacksAsyncWithHttpInfo
     *
     * Re-send callbacks (bulk)
     *
     * @param  \OpenAPI\Client\Model\ResendUserCallbacksRequest $resend_user_callbacks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resendUserCallbacksAsyncWithHttpInfo($resend_user_callbacks_request, string $contentType = self::contentTypes['resendUserCallbacks'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ResendUserCallbacks200Response';
        $request = $this->resendUserCallbacksRequest($resend_user_callbacks_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resendUserCallbacks'
     *
     * @param  \OpenAPI\Client\Model\ResendUserCallbacksRequest $resend_user_callbacks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resendUserCallbacks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resendUserCallbacksRequest($resend_user_callbacks_request, string $contentType = self::contentTypes['resendUserCallbacks'][0])
    {

        // verify the required parameter 'resend_user_callbacks_request' is set
        if ($resend_user_callbacks_request === null || (is_array($resend_user_callbacks_request) && count($resend_user_callbacks_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $resend_user_callbacks_request when calling resendUserCallbacks'
            );
        }


        $resourcePath = '/user/callbacks/resend';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($resend_user_callbacks_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($resend_user_callbacks_request));
            } else {
                $httpBody = $resend_user_callbacks_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
