<?php
/**
 * InfractionsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayZu Pix API
 *
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * InfractionsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfractionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getInfractions' => [
            'application/json',
        ],
        'getInfractionsById' => [
            'application/json',
        ],
        'getInfractionsDefenseById' => [
            'application/json',
        ],
        'getInfractionsDefenses' => [
            'application/json',
        ],
        'postInfractionsDefense' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getInfractions
     *
     * List Infractions
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 10)
     * @param  string|null $status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
     * @param  string|null $type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
     * @param  string|null $end_to_end_id end_to_end_id (optional)
     * @param  string|null $transaction_id transaction_id (optional)
     * @param  float|null $amount_min amount_min (optional)
     * @param  float|null $amount_max amount_max (optional)
     * @param  string|null $analysis_result Comma-separated AnalysisResult (optional)
     * @param  string|null $reported_by Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
     * @param  string|null $participant_document participant_document (optional)
     * @param  string|null $participant_name participant_name (optional)
     * @param  string|null $sort_by Campo de ordenação. (optional)
     * @param  string|null $sort_direction Direção da ordenação. (optional)
     * @param  \DateTime|null $reported_at_from Filtro: reportedAt a partir de. (optional)
     * @param  \DateTime|null $reported_at_to Filtro: reportedAt até. (optional)
     * @param  \DateTime|null $created_at_from Filtro: createdAt a partir de. (optional)
     * @param  \DateTime|null $created_at_to Filtro: createdAt até. (optional)
     * @param  \DateTime|null $expires_at_from Filtro: expiresAt a partir de. (optional)
     * @param  \DateTime|null $expires_at_to Filtro: expiresAt até. (optional)
     * @param  \DateTime|null $updated_at_from Filtro: updatedAt a partir de. (optional)
     * @param  \DateTime|null $updated_at_to Filtro: updatedAt até. (optional)
     * @param  bool|null $needs_manual_review Filtro: precisa de revisão manual. (optional)
     * @param  string|null $id Filtro por ID da infração. (optional)
     * @param  string|null $protocol Filtro por protocolo. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractions'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\InfractionListResponse|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getInfractions($content_type, $page = 1, $limit = 10, $status = null, $type = null, $end_to_end_id = null, $transaction_id = null, $amount_min = null, $amount_max = null, $analysis_result = null, $reported_by = null, $participant_document = null, $participant_name = null, $sort_by = null, $sort_direction = null, $reported_at_from = null, $reported_at_to = null, $created_at_from = null, $created_at_to = null, $expires_at_from = null, $expires_at_to = null, $updated_at_from = null, $updated_at_to = null, $needs_manual_review = null, $id = null, $protocol = null, string $contentType = self::contentTypes['getInfractions'][0])
    {
        list($response) = $this->getInfractionsWithHttpInfo($content_type, $page, $limit, $status, $type, $end_to_end_id, $transaction_id, $amount_min, $amount_max, $analysis_result, $reported_by, $participant_document, $participant_name, $sort_by, $sort_direction, $reported_at_from, $reported_at_to, $created_at_from, $created_at_to, $expires_at_from, $expires_at_to, $updated_at_from, $updated_at_to, $needs_manual_review, $id, $protocol, $contentType);
        return $response;
    }

    /**
     * Operation getInfractionsWithHttpInfo
     *
     * List Infractions
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
     * @param  string|null $type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
     * @param  string|null $end_to_end_id (optional)
     * @param  string|null $transaction_id (optional)
     * @param  float|null $amount_min (optional)
     * @param  float|null $amount_max (optional)
     * @param  string|null $analysis_result Comma-separated AnalysisResult (optional)
     * @param  string|null $reported_by Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
     * @param  string|null $participant_document (optional)
     * @param  string|null $participant_name (optional)
     * @param  string|null $sort_by Campo de ordenação. (optional)
     * @param  string|null $sort_direction Direção da ordenação. (optional)
     * @param  \DateTime|null $reported_at_from Filtro: reportedAt a partir de. (optional)
     * @param  \DateTime|null $reported_at_to Filtro: reportedAt até. (optional)
     * @param  \DateTime|null $created_at_from Filtro: createdAt a partir de. (optional)
     * @param  \DateTime|null $created_at_to Filtro: createdAt até. (optional)
     * @param  \DateTime|null $expires_at_from Filtro: expiresAt a partir de. (optional)
     * @param  \DateTime|null $expires_at_to Filtro: expiresAt até. (optional)
     * @param  \DateTime|null $updated_at_from Filtro: updatedAt a partir de. (optional)
     * @param  \DateTime|null $updated_at_to Filtro: updatedAt até. (optional)
     * @param  bool|null $needs_manual_review Filtro: precisa de revisão manual. (optional)
     * @param  string|null $id Filtro por ID da infração. (optional)
     * @param  string|null $protocol Filtro por protocolo. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractions'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\InfractionListResponse|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInfractionsWithHttpInfo($content_type, $page = 1, $limit = 10, $status = null, $type = null, $end_to_end_id = null, $transaction_id = null, $amount_min = null, $amount_max = null, $analysis_result = null, $reported_by = null, $participant_document = null, $participant_name = null, $sort_by = null, $sort_direction = null, $reported_at_from = null, $reported_at_to = null, $created_at_from = null, $created_at_to = null, $expires_at_from = null, $expires_at_to = null, $updated_at_from = null, $updated_at_to = null, $needs_manual_review = null, $id = null, $protocol = null, string $contentType = self::contentTypes['getInfractions'][0])
    {
        $request = $this->getInfractionsRequest($content_type, $page, $limit, $status, $type, $end_to_end_id, $transaction_id, $amount_min, $amount_max, $analysis_result, $reported_by, $participant_document, $participant_name, $sort_by, $sort_direction, $reported_at_from, $reported_at_to, $created_at_from, $created_at_to, $expires_at_from, $expires_at_to, $updated_at_from, $updated_at_to, $needs_manual_review, $id, $protocol, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InfractionListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\InfractionListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InfractionListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInfractionsAsync
     *
     * List Infractions
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
     * @param  string|null $type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
     * @param  string|null $end_to_end_id (optional)
     * @param  string|null $transaction_id (optional)
     * @param  float|null $amount_min (optional)
     * @param  float|null $amount_max (optional)
     * @param  string|null $analysis_result Comma-separated AnalysisResult (optional)
     * @param  string|null $reported_by Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
     * @param  string|null $participant_document (optional)
     * @param  string|null $participant_name (optional)
     * @param  string|null $sort_by Campo de ordenação. (optional)
     * @param  string|null $sort_direction Direção da ordenação. (optional)
     * @param  \DateTime|null $reported_at_from Filtro: reportedAt a partir de. (optional)
     * @param  \DateTime|null $reported_at_to Filtro: reportedAt até. (optional)
     * @param  \DateTime|null $created_at_from Filtro: createdAt a partir de. (optional)
     * @param  \DateTime|null $created_at_to Filtro: createdAt até. (optional)
     * @param  \DateTime|null $expires_at_from Filtro: expiresAt a partir de. (optional)
     * @param  \DateTime|null $expires_at_to Filtro: expiresAt até. (optional)
     * @param  \DateTime|null $updated_at_from Filtro: updatedAt a partir de. (optional)
     * @param  \DateTime|null $updated_at_to Filtro: updatedAt até. (optional)
     * @param  bool|null $needs_manual_review Filtro: precisa de revisão manual. (optional)
     * @param  string|null $id Filtro por ID da infração. (optional)
     * @param  string|null $protocol Filtro por protocolo. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsAsync($content_type, $page = 1, $limit = 10, $status = null, $type = null, $end_to_end_id = null, $transaction_id = null, $amount_min = null, $amount_max = null, $analysis_result = null, $reported_by = null, $participant_document = null, $participant_name = null, $sort_by = null, $sort_direction = null, $reported_at_from = null, $reported_at_to = null, $created_at_from = null, $created_at_to = null, $expires_at_from = null, $expires_at_to = null, $updated_at_from = null, $updated_at_to = null, $needs_manual_review = null, $id = null, $protocol = null, string $contentType = self::contentTypes['getInfractions'][0])
    {
        return $this->getInfractionsAsyncWithHttpInfo($content_type, $page, $limit, $status, $type, $end_to_end_id, $transaction_id, $amount_min, $amount_max, $analysis_result, $reported_by, $participant_document, $participant_name, $sort_by, $sort_direction, $reported_at_from, $reported_at_to, $created_at_from, $created_at_to, $expires_at_from, $expires_at_to, $updated_at_from, $updated_at_to, $needs_manual_review, $id, $protocol, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInfractionsAsyncWithHttpInfo
     *
     * List Infractions
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
     * @param  string|null $type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
     * @param  string|null $end_to_end_id (optional)
     * @param  string|null $transaction_id (optional)
     * @param  float|null $amount_min (optional)
     * @param  float|null $amount_max (optional)
     * @param  string|null $analysis_result Comma-separated AnalysisResult (optional)
     * @param  string|null $reported_by Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
     * @param  string|null $participant_document (optional)
     * @param  string|null $participant_name (optional)
     * @param  string|null $sort_by Campo de ordenação. (optional)
     * @param  string|null $sort_direction Direção da ordenação. (optional)
     * @param  \DateTime|null $reported_at_from Filtro: reportedAt a partir de. (optional)
     * @param  \DateTime|null $reported_at_to Filtro: reportedAt até. (optional)
     * @param  \DateTime|null $created_at_from Filtro: createdAt a partir de. (optional)
     * @param  \DateTime|null $created_at_to Filtro: createdAt até. (optional)
     * @param  \DateTime|null $expires_at_from Filtro: expiresAt a partir de. (optional)
     * @param  \DateTime|null $expires_at_to Filtro: expiresAt até. (optional)
     * @param  \DateTime|null $updated_at_from Filtro: updatedAt a partir de. (optional)
     * @param  \DateTime|null $updated_at_to Filtro: updatedAt até. (optional)
     * @param  bool|null $needs_manual_review Filtro: precisa de revisão manual. (optional)
     * @param  string|null $id Filtro por ID da infração. (optional)
     * @param  string|null $protocol Filtro por protocolo. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsAsyncWithHttpInfo($content_type, $page = 1, $limit = 10, $status = null, $type = null, $end_to_end_id = null, $transaction_id = null, $amount_min = null, $amount_max = null, $analysis_result = null, $reported_by = null, $participant_document = null, $participant_name = null, $sort_by = null, $sort_direction = null, $reported_at_from = null, $reported_at_to = null, $created_at_from = null, $created_at_to = null, $expires_at_from = null, $expires_at_to = null, $updated_at_from = null, $updated_at_to = null, $needs_manual_review = null, $id = null, $protocol = null, string $contentType = self::contentTypes['getInfractions'][0])
    {
        $returnType = '\OpenAPI\Client\Model\InfractionListResponse';
        $request = $this->getInfractionsRequest($content_type, $page, $limit, $status, $type, $end_to_end_id, $transaction_id, $amount_min, $amount_max, $analysis_result, $reported_by, $participant_document, $participant_name, $sort_by, $sort_direction, $reported_at_from, $reported_at_to, $created_at_from, $created_at_to, $expires_at_from, $expires_at_to, $updated_at_from, $updated_at_to, $needs_manual_review, $id, $protocol, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInfractions'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 10)
     * @param  string|null $status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
     * @param  string|null $type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
     * @param  string|null $end_to_end_id (optional)
     * @param  string|null $transaction_id (optional)
     * @param  float|null $amount_min (optional)
     * @param  float|null $amount_max (optional)
     * @param  string|null $analysis_result Comma-separated AnalysisResult (optional)
     * @param  string|null $reported_by Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
     * @param  string|null $participant_document (optional)
     * @param  string|null $participant_name (optional)
     * @param  string|null $sort_by Campo de ordenação. (optional)
     * @param  string|null $sort_direction Direção da ordenação. (optional)
     * @param  \DateTime|null $reported_at_from Filtro: reportedAt a partir de. (optional)
     * @param  \DateTime|null $reported_at_to Filtro: reportedAt até. (optional)
     * @param  \DateTime|null $created_at_from Filtro: createdAt a partir de. (optional)
     * @param  \DateTime|null $created_at_to Filtro: createdAt até. (optional)
     * @param  \DateTime|null $expires_at_from Filtro: expiresAt a partir de. (optional)
     * @param  \DateTime|null $expires_at_to Filtro: expiresAt até. (optional)
     * @param  \DateTime|null $updated_at_from Filtro: updatedAt a partir de. (optional)
     * @param  \DateTime|null $updated_at_to Filtro: updatedAt até. (optional)
     * @param  bool|null $needs_manual_review Filtro: precisa de revisão manual. (optional)
     * @param  string|null $id Filtro por ID da infração. (optional)
     * @param  string|null $protocol Filtro por protocolo. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInfractionsRequest($content_type, $page = 1, $limit = 10, $status = null, $type = null, $end_to_end_id = null, $transaction_id = null, $amount_min = null, $amount_max = null, $analysis_result = null, $reported_by = null, $participant_document = null, $participant_name = null, $sort_by = null, $sort_direction = null, $reported_at_from = null, $reported_at_to = null, $created_at_from = null, $created_at_to = null, $expires_at_from = null, $expires_at_to = null, $updated_at_from = null, $updated_at_to = null, $needs_manual_review = null, $id = null, $protocol = null, string $contentType = self::contentTypes['getInfractions'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getInfractions'
            );
        }

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling InfractionsApi.getInfractions, must be bigger than or equal to 1.');
        }
        
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling InfractionsApi.getInfractions, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling InfractionsApi.getInfractions, must be bigger than or equal to 1.');
        }
        
























        $resourcePath = '/user/infractions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_to_end_id,
            'endToEndId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transaction_id,
            'transactionId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_min,
            'amountMin', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_max,
            'amountMax', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $analysis_result,
            'analysisResult', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reported_by,
            'reportedBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $participant_document,
            'participantDocument', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $participant_name,
            'participantName', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sortBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sortDirection', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reported_at_from,
            'reportedAtFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reported_at_to,
            'reportedAtTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at_from,
            'createdAtFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at_to,
            'createdAtTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expires_at_from,
            'expiresAtFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expires_at_to,
            'expiresAtTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $updated_at_from,
            'updatedAtFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $updated_at_to,
            'updatedAtTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $needs_manual_review,
            'needsManualReview', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $protocol,
            'protocol', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getInfractionsById
     *
     * Get Infraction
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\InfractionDetail|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getInfractionsById($content_type, $id, string $contentType = self::contentTypes['getInfractionsById'][0])
    {
        list($response) = $this->getInfractionsByIdWithHttpInfo($content_type, $id, $contentType);
        return $response;
    }

    /**
     * Operation getInfractionsByIdWithHttpInfo
     *
     * Get Infraction
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\InfractionDetail|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInfractionsByIdWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getInfractionsById'][0])
    {
        $request = $this->getInfractionsByIdRequest($content_type, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\InfractionDetail',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\InfractionDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\InfractionDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInfractionsByIdAsync
     *
     * Get Infraction
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsByIdAsync($content_type, $id, string $contentType = self::contentTypes['getInfractionsById'][0])
    {
        return $this->getInfractionsByIdAsyncWithHttpInfo($content_type, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInfractionsByIdAsyncWithHttpInfo
     *
     * Get Infraction
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsByIdAsyncWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getInfractionsById'][0])
    {
        $returnType = '\OpenAPI\Client\Model\InfractionDetail';
        $request = $this->getInfractionsByIdRequest($content_type, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInfractionsById'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInfractionsByIdRequest($content_type, $id, string $contentType = self::contentTypes['getInfractionsById'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getInfractionsById'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getInfractionsById'
            );
        }


        $resourcePath = '/user/infractions/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getInfractionsDefenseById
     *
     * Get Defense
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $infraction_id Infraction ID (required)
     * @param  string $defense_id Defense ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenseById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Defense|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getInfractionsDefenseById($content_type, $infraction_id, $defense_id, string $contentType = self::contentTypes['getInfractionsDefenseById'][0])
    {
        list($response) = $this->getInfractionsDefenseByIdWithHttpInfo($content_type, $infraction_id, $defense_id, $contentType);
        return $response;
    }

    /**
     * Operation getInfractionsDefenseByIdWithHttpInfo
     *
     * Get Defense
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $infraction_id Infraction ID (required)
     * @param  string $defense_id Defense ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenseById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Defense|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInfractionsDefenseByIdWithHttpInfo($content_type, $infraction_id, $defense_id, string $contentType = self::contentTypes['getInfractionsDefenseById'][0])
    {
        $request = $this->getInfractionsDefenseByIdRequest($content_type, $infraction_id, $defense_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Defense',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Defense',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Defense',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInfractionsDefenseByIdAsync
     *
     * Get Defense
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $infraction_id Infraction ID (required)
     * @param  string $defense_id Defense ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenseById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsDefenseByIdAsync($content_type, $infraction_id, $defense_id, string $contentType = self::contentTypes['getInfractionsDefenseById'][0])
    {
        return $this->getInfractionsDefenseByIdAsyncWithHttpInfo($content_type, $infraction_id, $defense_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInfractionsDefenseByIdAsyncWithHttpInfo
     *
     * Get Defense
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $infraction_id Infraction ID (required)
     * @param  string $defense_id Defense ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenseById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsDefenseByIdAsyncWithHttpInfo($content_type, $infraction_id, $defense_id, string $contentType = self::contentTypes['getInfractionsDefenseById'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Defense';
        $request = $this->getInfractionsDefenseByIdRequest($content_type, $infraction_id, $defense_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInfractionsDefenseById'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $infraction_id Infraction ID (required)
     * @param  string $defense_id Defense ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenseById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInfractionsDefenseByIdRequest($content_type, $infraction_id, $defense_id, string $contentType = self::contentTypes['getInfractionsDefenseById'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getInfractionsDefenseById'
            );
        }

        // verify the required parameter 'infraction_id' is set
        if ($infraction_id === null || (is_array($infraction_id) && count($infraction_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $infraction_id when calling getInfractionsDefenseById'
            );
        }

        // verify the required parameter 'defense_id' is set
        if ($defense_id === null || (is_array($defense_id) && count($defense_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $defense_id when calling getInfractionsDefenseById'
            );
        }


        $resourcePath = '/user/infractions/{infractionId}/defenses/{defenseId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($infraction_id !== null) {
            $resourcePath = str_replace(
                '{infractionId}',
                ObjectSerializer::toPathValue($infraction_id),
                $resourcePath
            );
        }
        // path params
        if ($defense_id !== null) {
            $resourcePath = str_replace(
                '{defenseId}',
                ObjectSerializer::toPathValue($defense_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getInfractionsDefenses
     *
     * List Defenses
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Defense[]|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function getInfractionsDefenses($content_type, $id, string $contentType = self::contentTypes['getInfractionsDefenses'][0])
    {
        list($response) = $this->getInfractionsDefensesWithHttpInfo($content_type, $id, $contentType);
        return $response;
    }

    /**
     * Operation getInfractionsDefensesWithHttpInfo
     *
     * List Defenses
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenses'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Defense[]|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInfractionsDefensesWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getInfractionsDefenses'][0])
    {
        $request = $this->getInfractionsDefensesRequest($content_type, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Defense[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Defense[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Defense[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInfractionsDefensesAsync
     *
     * List Defenses
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsDefensesAsync($content_type, $id, string $contentType = self::contentTypes['getInfractionsDefenses'][0])
    {
        return $this->getInfractionsDefensesAsyncWithHttpInfo($content_type, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInfractionsDefensesAsyncWithHttpInfo
     *
     * List Defenses
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInfractionsDefensesAsyncWithHttpInfo($content_type, $id, string $contentType = self::contentTypes['getInfractionsDefenses'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Defense[]';
        $request = $this->getInfractionsDefensesRequest($content_type, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInfractionsDefenses'
     *
     * @param  string $content_type Obrigatório em toda chamada PayZu. (required)
     * @param  string $id Infraction ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInfractionsDefenses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInfractionsDefensesRequest($content_type, $id, string $contentType = self::contentTypes['getInfractionsDefenses'][0])
    {

        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling getInfractionsDefenses'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getInfractionsDefenses'
            );
        }


        $resourcePath = '/user/infractions/{id}/defenses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postInfractionsDefense
     *
     * Create Defense
     *
     * @param  string $id Infraction ID (required)
     * @param  string $defense Defense text (max: 1000 characters) (required)
     * @param  \SplFileObject[]|null $files Evidence files (max: 10MB total) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInfractionsDefense'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Defense|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response
     */
    public function postInfractionsDefense($id, $defense, $files = null, string $contentType = self::contentTypes['postInfractionsDefense'][0])
    {
        list($response) = $this->postInfractionsDefenseWithHttpInfo($id, $defense, $files, $contentType);
        return $response;
    }

    /**
     * Operation postInfractionsDefenseWithHttpInfo
     *
     * Create Defense
     *
     * @param  string $id Infraction ID (required)
     * @param  string $defense Defense text (max: 1000 characters) (required)
     * @param  \SplFileObject[]|null $files Evidence files (max: 10MB total) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInfractionsDefense'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Defense|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response|\OpenAPI\Client\Model\GetPix400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function postInfractionsDefenseWithHttpInfo($id, $defense, $files = null, string $contentType = self::contentTypes['postInfractionsDefense'][0])
    {
        $request = $this->postInfractionsDefenseRequest($id, $defense, $files, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\Defense',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\Defense',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Defense',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPix400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postInfractionsDefenseAsync
     *
     * Create Defense
     *
     * @param  string $id Infraction ID (required)
     * @param  string $defense Defense text (max: 1000 characters) (required)
     * @param  \SplFileObject[]|null $files Evidence files (max: 10MB total) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInfractionsDefense'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postInfractionsDefenseAsync($id, $defense, $files = null, string $contentType = self::contentTypes['postInfractionsDefense'][0])
    {
        return $this->postInfractionsDefenseAsyncWithHttpInfo($id, $defense, $files, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postInfractionsDefenseAsyncWithHttpInfo
     *
     * Create Defense
     *
     * @param  string $id Infraction ID (required)
     * @param  string $defense Defense text (max: 1000 characters) (required)
     * @param  \SplFileObject[]|null $files Evidence files (max: 10MB total) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInfractionsDefense'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postInfractionsDefenseAsyncWithHttpInfo($id, $defense, $files = null, string $contentType = self::contentTypes['postInfractionsDefense'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Defense';
        $request = $this->postInfractionsDefenseRequest($id, $defense, $files, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postInfractionsDefense'
     *
     * @param  string $id Infraction ID (required)
     * @param  string $defense Defense text (max: 1000 characters) (required)
     * @param  \SplFileObject[]|null $files Evidence files (max: 10MB total) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInfractionsDefense'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postInfractionsDefenseRequest($id, $defense, $files = null, string $contentType = self::contentTypes['postInfractionsDefense'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling postInfractionsDefense'
            );
        }

        // verify the required parameter 'defense' is set
        if ($defense === null || (is_array($defense) && count($defense) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $defense when calling postInfractionsDefense'
            );
        }
        if (strlen($defense) > 1000) {
            throw new \InvalidArgumentException('invalid length for "$defense" when calling InfractionsApi.postInfractionsDefense, must be smaller than or equal to 1000.');
        }
        


        $resourcePath = '/user/infractions/{id}/defenses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'defense' => $defense,
            'files' => $files,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
