/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Defense,
    DefenseFromJSON,
    DefenseToJSON,
} from '../models/Defense';
import {
    type GetPix400Response,
    GetPix400ResponseFromJSON,
    GetPix400ResponseToJSON,
} from '../models/GetPix400Response';
import {
    type InfractionDetail,
    InfractionDetailFromJSON,
    InfractionDetailToJSON,
} from '../models/InfractionDetail';
import {
    type InfractionListResponse,
    InfractionListResponseFromJSON,
    InfractionListResponseToJSON,
} from '../models/InfractionListResponse';

export interface GetInfractionsRequest {
    contentType: GetInfractionsContentTypeEnum;
    page?: number;
    limit?: number;
    status?: string;
    type?: string;
    endToEndId?: string;
    transactionId?: string;
    amountMin?: number;
    amountMax?: number;
    analysisResult?: string;
    reportedBy?: string;
    participantDocument?: string;
    participantName?: string;
    sortBy?: string;
    sortDirection?: GetInfractionsSortDirectionEnum;
    reportedAtFrom?: Date;
    reportedAtTo?: Date;
    createdAtFrom?: Date;
    createdAtTo?: Date;
    expiresAtFrom?: Date;
    expiresAtTo?: Date;
    updatedAtFrom?: Date;
    updatedAtTo?: Date;
    needsManualReview?: boolean;
    id?: string;
    protocol?: string;
}

export interface GetInfractionsByIdRequest {
    contentType: GetInfractionsByIdContentTypeEnum;
    id: string;
}

export interface GetInfractionsDefenseByIdRequest {
    contentType: GetInfractionsDefenseByIdContentTypeEnum;
    infractionId: string;
    defenseId: string;
}

export interface GetInfractionsDefensesRequest {
    contentType: GetInfractionsDefensesContentTypeEnum;
    id: string;
}

export interface PostInfractionsDefenseRequest {
    id: string;
    defense: string;
    files?: Array<Blob>;
}

/**
 * InfractionsApi - interface
 * 
 * @export
 * @interface InfractionsApiInterface
 */
export interface InfractionsApiInterface {
    /**
     * Creates request options for getInfractions without sending the request
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {string} [status] Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS)
     * @param {string} [type] Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED)
     * @param {string} [endToEndId] 
     * @param {string} [transactionId] 
     * @param {number} [amountMin] 
     * @param {number} [amountMax] 
     * @param {string} [analysisResult] Comma-separated AnalysisResult
     * @param {string} [reportedBy] Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT)
     * @param {string} [participantDocument] 
     * @param {string} [participantName] 
     * @param {string} [sortBy] Campo de ordenação.
     * @param {'asc' | 'desc'} [sortDirection] Direção da ordenação.
     * @param {Date} [reportedAtFrom] Filtro: reportedAt a partir de.
     * @param {Date} [reportedAtTo] Filtro: reportedAt até.
     * @param {Date} [createdAtFrom] Filtro: createdAt a partir de.
     * @param {Date} [createdAtTo] Filtro: createdAt até.
     * @param {Date} [expiresAtFrom] Filtro: expiresAt a partir de.
     * @param {Date} [expiresAtTo] Filtro: expiresAt até.
     * @param {Date} [updatedAtFrom] Filtro: updatedAt a partir de.
     * @param {Date} [updatedAtTo] Filtro: updatedAt até.
     * @param {boolean} [needsManualReview] Filtro: precisa de revisão manual.
     * @param {string} [id] Filtro por ID da infração.
     * @param {string} [protocol] Filtro por protocolo.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsRequestOpts(requestParameters: GetInfractionsRequest): Promise<runtime.RequestOpts>;

    /**
     * List all infractions for the authenticated user with pagination and filters.
     * @summary List Infractions
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {string} [status] Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS)
     * @param {string} [type] Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED)
     * @param {string} [endToEndId] 
     * @param {string} [transactionId] 
     * @param {number} [amountMin] 
     * @param {number} [amountMax] 
     * @param {string} [analysisResult] Comma-separated AnalysisResult
     * @param {string} [reportedBy] Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT)
     * @param {string} [participantDocument] 
     * @param {string} [participantName] 
     * @param {string} [sortBy] Campo de ordenação.
     * @param {'asc' | 'desc'} [sortDirection] Direção da ordenação.
     * @param {Date} [reportedAtFrom] Filtro: reportedAt a partir de.
     * @param {Date} [reportedAtTo] Filtro: reportedAt até.
     * @param {Date} [createdAtFrom] Filtro: createdAt a partir de.
     * @param {Date} [createdAtTo] Filtro: createdAt até.
     * @param {Date} [expiresAtFrom] Filtro: expiresAt a partir de.
     * @param {Date} [expiresAtTo] Filtro: expiresAt até.
     * @param {Date} [updatedAtFrom] Filtro: updatedAt a partir de.
     * @param {Date} [updatedAtTo] Filtro: updatedAt até.
     * @param {boolean} [needsManualReview] Filtro: precisa de revisão manual.
     * @param {string} [id] Filtro por ID da infração.
     * @param {string} [protocol] Filtro por protocolo.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsRaw(requestParameters: GetInfractionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfractionListResponse>>;

    /**
     * List all infractions for the authenticated user with pagination and filters.
     * List Infractions
     */
    getInfractions(requestParameters: GetInfractionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfractionListResponse>;

    /**
     * Creates request options for getInfractionsById without sending the request
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} id Infraction ID
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsByIdRequestOpts(requestParameters: GetInfractionsByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a specific infraction by ID.
     * @summary Get Infraction
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} id Infraction ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsByIdRaw(requestParameters: GetInfractionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfractionDetail>>;

    /**
     * Get a specific infraction by ID.
     * Get Infraction
     */
    getInfractionsById(requestParameters: GetInfractionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfractionDetail>;

    /**
     * Creates request options for getInfractionsDefenseById without sending the request
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} infractionId Infraction ID
     * @param {string} defenseId Defense ID
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsDefenseByIdRequestOpts(requestParameters: GetInfractionsDefenseByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a specific defense for an infraction. **Requires support privileges**.
     * @summary Get Defense
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} infractionId Infraction ID
     * @param {string} defenseId Defense ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsDefenseByIdRaw(requestParameters: GetInfractionsDefenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defense>>;

    /**
     * Get a specific defense for an infraction. **Requires support privileges**.
     * Get Defense
     */
    getInfractionsDefenseById(requestParameters: GetInfractionsDefenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defense>;

    /**
     * Creates request options for getInfractionsDefenses without sending the request
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} id Infraction ID
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsDefensesRequestOpts(requestParameters: GetInfractionsDefensesRequest): Promise<runtime.RequestOpts>;

    /**
     * List all defenses for a specific infraction. **Requires support privileges**.
     * @summary List Defenses
     * @param {'application/json'} contentType Obrigatório em toda chamada PayZu.
     * @param {string} id Infraction ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    getInfractionsDefensesRaw(requestParameters: GetInfractionsDefensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Defense>>>;

    /**
     * List all defenses for a specific infraction. **Requires support privileges**.
     * List Defenses
     */
    getInfractionsDefenses(requestParameters: GetInfractionsDefensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Defense>>;

    /**
     * Creates request options for postInfractionsDefense without sending the request
     * @param {string} id Infraction ID
     * @param {string} defense Defense text (max: 1000 characters)
     * @param {Array<Blob>} [files] Evidence files (max: 10MB total)
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    postInfractionsDefenseRequestOpts(requestParameters: PostInfractionsDefenseRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a defense for a specific infraction.
     * @summary Create Defense
     * @param {string} id Infraction ID
     * @param {string} defense Defense text (max: 1000 characters)
     * @param {Array<Blob>} [files] Evidence files (max: 10MB total)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfractionsApiInterface
     */
    postInfractionsDefenseRaw(requestParameters: PostInfractionsDefenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defense>>;

    /**
     * Create a defense for a specific infraction.
     * Create Defense
     */
    postInfractionsDefense(requestParameters: PostInfractionsDefenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defense>;

}

/**
 * 
 */
export class InfractionsApi extends runtime.BaseAPI implements InfractionsApiInterface {

    /**
     * Creates request options for getInfractions without sending the request
     */
    async getInfractionsRequestOpts(requestParameters: GetInfractionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling getInfractions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['endToEndId'] != null) {
            queryParameters['endToEndId'] = requestParameters['endToEndId'];
        }

        if (requestParameters['transactionId'] != null) {
            queryParameters['transactionId'] = requestParameters['transactionId'];
        }

        if (requestParameters['amountMin'] != null) {
            queryParameters['amountMin'] = requestParameters['amountMin'];
        }

        if (requestParameters['amountMax'] != null) {
            queryParameters['amountMax'] = requestParameters['amountMax'];
        }

        if (requestParameters['analysisResult'] != null) {
            queryParameters['analysisResult'] = requestParameters['analysisResult'];
        }

        if (requestParameters['reportedBy'] != null) {
            queryParameters['reportedBy'] = requestParameters['reportedBy'];
        }

        if (requestParameters['participantDocument'] != null) {
            queryParameters['participantDocument'] = requestParameters['participantDocument'];
        }

        if (requestParameters['participantName'] != null) {
            queryParameters['participantName'] = requestParameters['participantName'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sortDirection'] = requestParameters['sortDirection'];
        }

        if (requestParameters['reportedAtFrom'] != null) {
            queryParameters['reportedAtFrom'] = (requestParameters['reportedAtFrom'] as any).toISOString();
        }

        if (requestParameters['reportedAtTo'] != null) {
            queryParameters['reportedAtTo'] = (requestParameters['reportedAtTo'] as any).toISOString();
        }

        if (requestParameters['createdAtFrom'] != null) {
            queryParameters['createdAtFrom'] = (requestParameters['createdAtFrom'] as any).toISOString();
        }

        if (requestParameters['createdAtTo'] != null) {
            queryParameters['createdAtTo'] = (requestParameters['createdAtTo'] as any).toISOString();
        }

        if (requestParameters['expiresAtFrom'] != null) {
            queryParameters['expiresAtFrom'] = (requestParameters['expiresAtFrom'] as any).toISOString();
        }

        if (requestParameters['expiresAtTo'] != null) {
            queryParameters['expiresAtTo'] = (requestParameters['expiresAtTo'] as any).toISOString();
        }

        if (requestParameters['updatedAtFrom'] != null) {
            queryParameters['updatedAtFrom'] = (requestParameters['updatedAtFrom'] as any).toISOString();
        }

        if (requestParameters['updatedAtTo'] != null) {
            queryParameters['updatedAtTo'] = (requestParameters['updatedAtTo'] as any).toISOString();
        }

        if (requestParameters['needsManualReview'] != null) {
            queryParameters['needsManualReview'] = requestParameters['needsManualReview'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['protocol'] != null) {
            queryParameters['protocol'] = requestParameters['protocol'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/infractions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all infractions for the authenticated user with pagination and filters.
     * List Infractions
     */
    async getInfractionsRaw(requestParameters: GetInfractionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfractionListResponse>> {
        const requestOptions = await this.getInfractionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfractionListResponseFromJSON(jsonValue));
    }

    /**
     * List all infractions for the authenticated user with pagination and filters.
     * List Infractions
     */
    async getInfractions(requestParameters: GetInfractionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfractionListResponse> {
        const response = await this.getInfractionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInfractionsById without sending the request
     */
    async getInfractionsByIdRequestOpts(requestParameters: GetInfractionsByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling getInfractionsById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInfractionsById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/infractions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific infraction by ID.
     * Get Infraction
     */
    async getInfractionsByIdRaw(requestParameters: GetInfractionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfractionDetail>> {
        const requestOptions = await this.getInfractionsByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfractionDetailFromJSON(jsonValue));
    }

    /**
     * Get a specific infraction by ID.
     * Get Infraction
     */
    async getInfractionsById(requestParameters: GetInfractionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfractionDetail> {
        const response = await this.getInfractionsByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInfractionsDefenseById without sending the request
     */
    async getInfractionsDefenseByIdRequestOpts(requestParameters: GetInfractionsDefenseByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling getInfractionsDefenseById().'
            );
        }

        if (requestParameters['infractionId'] == null) {
            throw new runtime.RequiredError(
                'infractionId',
                'Required parameter "infractionId" was null or undefined when calling getInfractionsDefenseById().'
            );
        }

        if (requestParameters['defenseId'] == null) {
            throw new runtime.RequiredError(
                'defenseId',
                'Required parameter "defenseId" was null or undefined when calling getInfractionsDefenseById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/infractions/{infractionId}/defenses/{defenseId}`;
        urlPath = urlPath.replace('{infractionId}', encodeURIComponent(String(requestParameters['infractionId'])));
        urlPath = urlPath.replace('{defenseId}', encodeURIComponent(String(requestParameters['defenseId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific defense for an infraction. **Requires support privileges**.
     * Get Defense
     */
    async getInfractionsDefenseByIdRaw(requestParameters: GetInfractionsDefenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defense>> {
        const requestOptions = await this.getInfractionsDefenseByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefenseFromJSON(jsonValue));
    }

    /**
     * Get a specific defense for an infraction. **Requires support privileges**.
     * Get Defense
     */
    async getInfractionsDefenseById(requestParameters: GetInfractionsDefenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defense> {
        const response = await this.getInfractionsDefenseByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInfractionsDefenses without sending the request
     */
    async getInfractionsDefensesRequestOpts(requestParameters: GetInfractionsDefensesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling getInfractionsDefenses().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInfractionsDefenses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/infractions/{id}/defenses`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all defenses for a specific infraction. **Requires support privileges**.
     * List Defenses
     */
    async getInfractionsDefensesRaw(requestParameters: GetInfractionsDefensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Defense>>> {
        const requestOptions = await this.getInfractionsDefensesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DefenseFromJSON));
    }

    /**
     * List all defenses for a specific infraction. **Requires support privileges**.
     * List Defenses
     */
    async getInfractionsDefenses(requestParameters: GetInfractionsDefensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Defense>> {
        const response = await this.getInfractionsDefensesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postInfractionsDefense without sending the request
     */
    async postInfractionsDefenseRequestOpts(requestParameters: PostInfractionsDefenseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling postInfractionsDefense().'
            );
        }

        if (requestParameters['defense'] == null) {
            throw new runtime.RequiredError(
                'defense',
                'Required parameter "defense" was null or undefined when calling postInfractionsDefense().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['defense'] != null) {
            formParams.append('defense', requestParameters['defense'] as any);
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }


        let urlPath = `/user/infractions/{id}/defenses`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Create a defense for a specific infraction.
     * Create Defense
     */
    async postInfractionsDefenseRaw(requestParameters: PostInfractionsDefenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Defense>> {
        const requestOptions = await this.postInfractionsDefenseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefenseFromJSON(jsonValue));
    }

    /**
     * Create a defense for a specific infraction.
     * Create Defense
     */
    async postInfractionsDefense(requestParameters: PostInfractionsDefenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Defense> {
        const response = await this.postInfractionsDefenseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetInfractionsContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetInfractionsContentTypeEnum = typeof GetInfractionsContentTypeEnum[keyof typeof GetInfractionsContentTypeEnum];
/**
 * @export
 */
export const GetInfractionsSortDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetInfractionsSortDirectionEnum = typeof GetInfractionsSortDirectionEnum[keyof typeof GetInfractionsSortDirectionEnum];
/**
 * @export
 */
export const GetInfractionsByIdContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetInfractionsByIdContentTypeEnum = typeof GetInfractionsByIdContentTypeEnum[keyof typeof GetInfractionsByIdContentTypeEnum];
/**
 * @export
 */
export const GetInfractionsDefenseByIdContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetInfractionsDefenseByIdContentTypeEnum = typeof GetInfractionsDefenseByIdContentTypeEnum[keyof typeof GetInfractionsDefenseByIdContentTypeEnum];
/**
 * @export
 */
export const GetInfractionsDefensesContentTypeEnum = {
    ApplicationJson: 'application/json'
} as const;
export type GetInfractionsDefensesContentTypeEnum = typeof GetInfractionsDefensesContentTypeEnum[keyof typeof GetInfractionsDefensesContentTypeEnum];
