/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallbackDetail } from './CallbackDetail';
import {
    CallbackDetailFromJSON,
    CallbackDetailFromJSONTyped,
    CallbackDetailToJSON,
    CallbackDetailToJSONTyped,
} from './CallbackDetail';
import type { CallbackListResponsePagination } from './CallbackListResponsePagination';
import {
    CallbackListResponsePaginationFromJSON,
    CallbackListResponsePaginationFromJSONTyped,
    CallbackListResponsePaginationToJSON,
    CallbackListResponsePaginationToJSONTyped,
} from './CallbackListResponsePagination';

/**
 * 
 * @export
 * @interface CallbackListResponse
 */
export interface CallbackListResponse {
    /**
     * 
     * @type {CallbackListResponsePagination}
     * @memberof CallbackListResponse
     */
    pagination?: CallbackListResponsePagination;
    /**
     * Array of callback logs
     * @type {Array<CallbackDetail>}
     * @memberof CallbackListResponse
     */
    callbacks?: Array<CallbackDetail>;
}

/**
 * Check if a given object implements the CallbackListResponse interface.
 */
export function instanceOfCallbackListResponse(value: object): value is CallbackListResponse {
    return true;
}

export function CallbackListResponseFromJSON(json: any): CallbackListResponse {
    return CallbackListResponseFromJSONTyped(json, false);
}

export function CallbackListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallbackListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : CallbackListResponsePaginationFromJSON(json['pagination']),
        'callbacks': json['callbacks'] == null ? undefined : ((json['callbacks'] as Array<any>).map(CallbackDetailFromJSON)),
    };
}

export function CallbackListResponseToJSON(json: any): CallbackListResponse {
    return CallbackListResponseToJSONTyped(json, false);
}

export function CallbackListResponseToJSONTyped(value?: CallbackListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': CallbackListResponsePaginationToJSON(value['pagination']),
        'callbacks': value['callbacks'] == null ? undefined : ((value['callbacks'] as Array<any>).map(CallbackDetailToJSON)),
    };
}

