/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefenseFilesInner
 */
export interface DefenseFilesInner {
    /**
     * 
     * @type {string}
     * @memberof DefenseFilesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DefenseFilesInner
     */
    mimeType?: string;
    /**
     * 
     * @type {number}
     * @memberof DefenseFilesInner
     */
    size?: number;
    /**
     * URL assinada para download (expira em 9 minutos). Presente apenas ao buscar a defesa individual; ausente na listagem.
     * @type {string}
     * @memberof DefenseFilesInner
     */
    url?: string;
}

/**
 * Check if a given object implements the DefenseFilesInner interface.
 */
export function instanceOfDefenseFilesInner(value: object): value is DefenseFilesInner {
    return true;
}

export function DefenseFilesInnerFromJSON(json: any): DefenseFilesInner {
    return DefenseFilesInnerFromJSONTyped(json, false);
}

export function DefenseFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefenseFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DefenseFilesInnerToJSON(json: any): DefenseFilesInner {
    return DefenseFilesInnerToJSONTyped(json, false);
}

export function DefenseFilesInnerToJSONTyped(value?: DefenseFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'mimeType': value['mimeType'],
        'size': value['size'],
        'url': value['url'],
    };
}

