/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPixKey404Response
 */
export interface GetPixKey404Response {
    /**
     * 
     * @type {string}
     * @memberof GetPixKey404Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPixKey404Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GetPixKey404Response interface.
 */
export function instanceOfGetPixKey404Response(value: object): value is GetPixKey404Response {
    return true;
}

export function GetPixKey404ResponseFromJSON(json: any): GetPixKey404Response {
    return GetPixKey404ResponseFromJSONTyped(json, false);
}

export function GetPixKey404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPixKey404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetPixKey404ResponseToJSON(json: any): GetPixKey404Response {
    return GetPixKey404ResponseToJSONTyped(json, false);
}

export function GetPixKey404ResponseToJSONTyped(value?: GetPixKey404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

