/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install @payzu/pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWithdrawQrcodeRequest
 */
export interface PostWithdrawQrcodeRequest {
    /**
     * Pix QR Code payload (EMV format).
     * @type {string}
     * @memberof PostWithdrawQrcodeRequest
     */
    qrCode: string;
    /**
     * Amount in BRL. Optional - if not provided, uses the QR Code's embedded value.
     * @type {number}
     * @memberof PostWithdrawQrcodeRequest
     */
    amount?: number;
    /**
     * Webhook URL for status updates.
     * @type {string}
     * @memberof PostWithdrawQrcodeRequest
     */
    callbackUrl?: string;
    /**
     * Optional description for the payment.
     * @type {string}
     * @memberof PostWithdrawQrcodeRequest
     */
    description?: string;
    /**
     * External reference for this withdrawal.
     * @type {string}
     * @memberof PostWithdrawQrcodeRequest
     */
    clientReference?: string;
    /**
     * Subconta virtual (até 50 caracteres) para correlacionar lojas, filiais, marketplaces. Volta no callback.
     * @type {string}
     * @memberof PostWithdrawQrcodeRequest
     */
    virtualAccount?: string;
}

/**
 * Check if a given object implements the PostWithdrawQrcodeRequest interface.
 */
export function instanceOfPostWithdrawQrcodeRequest(value: object): value is PostWithdrawQrcodeRequest {
    if (!('qrCode' in value) || value['qrCode'] === undefined) return false;
    return true;
}

export function PostWithdrawQrcodeRequestFromJSON(json: any): PostWithdrawQrcodeRequest {
    return PostWithdrawQrcodeRequestFromJSONTyped(json, false);
}

export function PostWithdrawQrcodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWithdrawQrcodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'qrCode': json['qrCode'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'callbackUrl': json['callbackUrl'] == null ? undefined : json['callbackUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'clientReference': json['clientReference'] == null ? undefined : json['clientReference'],
        'virtualAccount': json['virtualAccount'] == null ? undefined : json['virtualAccount'],
    };
}

export function PostWithdrawQrcodeRequestToJSON(json: any): PostWithdrawQrcodeRequest {
    return PostWithdrawQrcodeRequestToJSONTyped(json, false);
}

export function PostWithdrawQrcodeRequestToJSONTyped(value?: PostWithdrawQrcodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrCode': value['qrCode'],
        'amount': value['amount'],
        'callbackUrl': value['callbackUrl'],
        'description': value['description'],
        'clientReference': value['clientReference'],
        'virtualAccount': value['virtualAccount'],
    };
}

