/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWithdrawQrcode400Response
 */
export interface PostWithdrawQrcode400Response {
    /**
     * 
     * @type {string}
     * @memberof PostWithdrawQrcode400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PostWithdrawQrcode400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PostWithdrawQrcode400Response interface.
 */
export function instanceOfPostWithdrawQrcode400Response(value: object): value is PostWithdrawQrcode400Response {
    return true;
}

export function PostWithdrawQrcode400ResponseFromJSON(json: any): PostWithdrawQrcode400Response {
    return PostWithdrawQrcode400ResponseFromJSONTyped(json, false);
}

export function PostWithdrawQrcode400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWithdrawQrcode400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PostWithdrawQrcode400ResponseToJSON(json: any): PostWithdrawQrcode400Response {
    return PostWithdrawQrcode400ResponseToJSONTyped(json, false);
}

export function PostWithdrawQrcode400ResponseToJSONTyped(value?: PostWithdrawQrcode400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

