/* tslint:disable */
/* eslint-disable */
/**
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install @payzu/pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Decoded information from a Pix QR Code.
 * @export
 * @interface QRCodeReadResponse
 */
export interface QRCodeReadResponse {
    /**
     * Type of QR Code.
     * @type {QRCodeReadResponseQrCodeTypeEnum}
     * @memberof QRCodeReadResponse
     */
    qrCodeType?: QRCodeReadResponseQrCodeTypeEnum;
    /**
     * Name of the payment receiver.
     * @type {string}
     * @memberof QRCodeReadResponse
     */
    name?: string;
    /**
     * CPF or CNPJ of the receiver.
     * @type {string}
     * @memberof QRCodeReadResponse
     */
    document?: string;
    /**
     * Amount to be paid (may differ from originalAmount for dynamic QR Codes).
     * @type {number}
     * @memberof QRCodeReadResponse
     */
    amount?: number;
    /**
     * Original amount embedded in the QR Code.
     * @type {number}
     * @memberof QRCodeReadResponse
     */
    originalAmount?: number;
    /**
     * Transaction identifier.
     * @type {string}
     * @memberof QRCodeReadResponse
     */
    txid?: string;
    /**
     * Additional information or description.
     * @type {string}
     * @memberof QRCodeReadResponse
     */
    additionalInfo?: string;
    /**
     * Seconds until QR Code expires (0 for static QR Codes).
     * @type {number}
     * @memberof QRCodeReadResponse
     */
    expiresIn?: number;
    /**
     * Creation date of the QR Code (for dynamic QR Codes).
     * @type {Date}
     * @memberof QRCodeReadResponse
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const QRCodeReadResponseQrCodeTypeEnum = {
    Static: 'STATIC',
    Dynamic: 'DYNAMIC'
} as const;
export type QRCodeReadResponseQrCodeTypeEnum = typeof QRCodeReadResponseQrCodeTypeEnum[keyof typeof QRCodeReadResponseQrCodeTypeEnum];


/**
 * Check if a given object implements the QRCodeReadResponse interface.
 */
export function instanceOfQRCodeReadResponse(value: object): value is QRCodeReadResponse {
    return true;
}

export function QRCodeReadResponseFromJSON(json: any): QRCodeReadResponse {
    return QRCodeReadResponseFromJSONTyped(json, false);
}

export function QRCodeReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qrCodeType': json['qrCodeType'] == null ? undefined : json['qrCodeType'],
        'name': json['name'] == null ? undefined : json['name'],
        'document': json['document'] == null ? undefined : json['document'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'originalAmount': json['originalAmount'] == null ? undefined : json['originalAmount'],
        'txid': json['txid'] == null ? undefined : json['txid'],
        'additionalInfo': json['additionalInfo'] == null ? undefined : json['additionalInfo'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function QRCodeReadResponseToJSON(json: any): QRCodeReadResponse {
    return QRCodeReadResponseToJSONTyped(json, false);
}

export function QRCodeReadResponseToJSONTyped(value?: QRCodeReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrCodeType': value['qrCodeType'],
        'name': value['name'],
        'document': value['document'],
        'amount': value['amount'],
        'originalAmount': value['originalAmount'],
        'txid': value['txid'],
        'additionalInfo': value['additionalInfo'],
        'expiresIn': value['expiresIn'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

