/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the TransactionInfraction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionInfraction{}

// TransactionInfraction Infraction details if the transaction has been disputed
type TransactionInfraction struct {
	Id *string `json:"id,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Status *string `json:"status,omitempty"`
	Type *string `json:"type,omitempty"`
	ReportDetails *string `json:"reportDetails,omitempty"`
	ReportedBy *string `json:"reportedBy,omitempty"`
	AnalysisResult *string `json:"analysisResult,omitempty"`
	AnalysisDetails *string `json:"analysisDetails,omitempty"`
	ReportedAt *time.Time `json:"reportedAt,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewTransactionInfraction instantiates a new TransactionInfraction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionInfraction() *TransactionInfraction {
	this := TransactionInfraction{}
	return &this
}

// NewTransactionInfractionWithDefaults instantiates a new TransactionInfraction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionInfractionWithDefaults() *TransactionInfraction {
	this := TransactionInfraction{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TransactionInfraction) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TransactionInfraction) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TransactionInfraction) SetId(v string) {
	o.Id = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *TransactionInfraction) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *TransactionInfraction) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *TransactionInfraction) SetProtocol(v string) {
	o.Protocol = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TransactionInfraction) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TransactionInfraction) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TransactionInfraction) SetStatus(v string) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TransactionInfraction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TransactionInfraction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TransactionInfraction) SetType(v string) {
	o.Type = &v
}

// GetReportDetails returns the ReportDetails field value if set, zero value otherwise.
func (o *TransactionInfraction) GetReportDetails() string {
	if o == nil || IsNil(o.ReportDetails) {
		var ret string
		return ret
	}
	return *o.ReportDetails
}

// GetReportDetailsOk returns a tuple with the ReportDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetReportDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.ReportDetails) {
		return nil, false
	}
	return o.ReportDetails, true
}

// HasReportDetails returns a boolean if a field has been set.
func (o *TransactionInfraction) HasReportDetails() bool {
	if o != nil && !IsNil(o.ReportDetails) {
		return true
	}

	return false
}

// SetReportDetails gets a reference to the given string and assigns it to the ReportDetails field.
func (o *TransactionInfraction) SetReportDetails(v string) {
	o.ReportDetails = &v
}

// GetReportedBy returns the ReportedBy field value if set, zero value otherwise.
func (o *TransactionInfraction) GetReportedBy() string {
	if o == nil || IsNil(o.ReportedBy) {
		var ret string
		return ret
	}
	return *o.ReportedBy
}

// GetReportedByOk returns a tuple with the ReportedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetReportedByOk() (*string, bool) {
	if o == nil || IsNil(o.ReportedBy) {
		return nil, false
	}
	return o.ReportedBy, true
}

// HasReportedBy returns a boolean if a field has been set.
func (o *TransactionInfraction) HasReportedBy() bool {
	if o != nil && !IsNil(o.ReportedBy) {
		return true
	}

	return false
}

// SetReportedBy gets a reference to the given string and assigns it to the ReportedBy field.
func (o *TransactionInfraction) SetReportedBy(v string) {
	o.ReportedBy = &v
}

// GetAnalysisResult returns the AnalysisResult field value if set, zero value otherwise.
func (o *TransactionInfraction) GetAnalysisResult() string {
	if o == nil || IsNil(o.AnalysisResult) {
		var ret string
		return ret
	}
	return *o.AnalysisResult
}

// GetAnalysisResultOk returns a tuple with the AnalysisResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetAnalysisResultOk() (*string, bool) {
	if o == nil || IsNil(o.AnalysisResult) {
		return nil, false
	}
	return o.AnalysisResult, true
}

// HasAnalysisResult returns a boolean if a field has been set.
func (o *TransactionInfraction) HasAnalysisResult() bool {
	if o != nil && !IsNil(o.AnalysisResult) {
		return true
	}

	return false
}

// SetAnalysisResult gets a reference to the given string and assigns it to the AnalysisResult field.
func (o *TransactionInfraction) SetAnalysisResult(v string) {
	o.AnalysisResult = &v
}

// GetAnalysisDetails returns the AnalysisDetails field value if set, zero value otherwise.
func (o *TransactionInfraction) GetAnalysisDetails() string {
	if o == nil || IsNil(o.AnalysisDetails) {
		var ret string
		return ret
	}
	return *o.AnalysisDetails
}

// GetAnalysisDetailsOk returns a tuple with the AnalysisDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetAnalysisDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.AnalysisDetails) {
		return nil, false
	}
	return o.AnalysisDetails, true
}

// HasAnalysisDetails returns a boolean if a field has been set.
func (o *TransactionInfraction) HasAnalysisDetails() bool {
	if o != nil && !IsNil(o.AnalysisDetails) {
		return true
	}

	return false
}

// SetAnalysisDetails gets a reference to the given string and assigns it to the AnalysisDetails field.
func (o *TransactionInfraction) SetAnalysisDetails(v string) {
	o.AnalysisDetails = &v
}

// GetReportedAt returns the ReportedAt field value if set, zero value otherwise.
func (o *TransactionInfraction) GetReportedAt() time.Time {
	if o == nil || IsNil(o.ReportedAt) {
		var ret time.Time
		return ret
	}
	return *o.ReportedAt
}

// GetReportedAtOk returns a tuple with the ReportedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetReportedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReportedAt) {
		return nil, false
	}
	return o.ReportedAt, true
}

// HasReportedAt returns a boolean if a field has been set.
func (o *TransactionInfraction) HasReportedAt() bool {
	if o != nil && !IsNil(o.ReportedAt) {
		return true
	}

	return false
}

// SetReportedAt gets a reference to the given time.Time and assigns it to the ReportedAt field.
func (o *TransactionInfraction) SetReportedAt(v time.Time) {
	o.ReportedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *TransactionInfraction) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *TransactionInfraction) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *TransactionInfraction) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TransactionInfraction) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TransactionInfraction) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TransactionInfraction) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *TransactionInfraction) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInfraction) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *TransactionInfraction) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *TransactionInfraction) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o TransactionInfraction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionInfraction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.ReportDetails) {
		toSerialize["reportDetails"] = o.ReportDetails
	}
	if !IsNil(o.ReportedBy) {
		toSerialize["reportedBy"] = o.ReportedBy
	}
	if !IsNil(o.AnalysisResult) {
		toSerialize["analysisResult"] = o.AnalysisResult
	}
	if !IsNil(o.AnalysisDetails) {
		toSerialize["analysisDetails"] = o.AnalysisDetails
	}
	if !IsNil(o.ReportedAt) {
		toSerialize["reportedAt"] = o.ReportedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableTransactionInfraction struct {
	value *TransactionInfraction
	isSet bool
}

func (v NullableTransactionInfraction) Get() *TransactionInfraction {
	return v.value
}

func (v *NullableTransactionInfraction) Set(val *TransactionInfraction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionInfraction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionInfraction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionInfraction(val *TransactionInfraction) *NullableTransactionInfraction {
	return &NullableTransactionInfraction{value: val, isSet: true}
}

func (v NullableTransactionInfraction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionInfraction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


