/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

API version: 1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
)

// checks if the CallbackListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallbackListResponse{}

// CallbackListResponse struct for CallbackListResponse
type CallbackListResponse struct {
	Pagination *CallbackListResponsePagination `json:"pagination,omitempty"`
	// Array of callback logs
	Callbacks []CallbackDetail `json:"callbacks,omitempty"`
}

// NewCallbackListResponse instantiates a new CallbackListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallbackListResponse() *CallbackListResponse {
	this := CallbackListResponse{}
	return &this
}

// NewCallbackListResponseWithDefaults instantiates a new CallbackListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallbackListResponseWithDefaults() *CallbackListResponse {
	this := CallbackListResponse{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *CallbackListResponse) GetPagination() CallbackListResponsePagination {
	if o == nil || IsNil(o.Pagination) {
		var ret CallbackListResponsePagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallbackListResponse) GetPaginationOk() (*CallbackListResponsePagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *CallbackListResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given CallbackListResponsePagination and assigns it to the Pagination field.
func (o *CallbackListResponse) SetPagination(v CallbackListResponsePagination) {
	o.Pagination = &v
}

// GetCallbacks returns the Callbacks field value if set, zero value otherwise.
func (o *CallbackListResponse) GetCallbacks() []CallbackDetail {
	if o == nil || IsNil(o.Callbacks) {
		var ret []CallbackDetail
		return ret
	}
	return o.Callbacks
}

// GetCallbacksOk returns a tuple with the Callbacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallbackListResponse) GetCallbacksOk() ([]CallbackDetail, bool) {
	if o == nil || IsNil(o.Callbacks) {
		return nil, false
	}
	return o.Callbacks, true
}

// HasCallbacks returns a boolean if a field has been set.
func (o *CallbackListResponse) HasCallbacks() bool {
	if o != nil && !IsNil(o.Callbacks) {
		return true
	}

	return false
}

// SetCallbacks gets a reference to the given []CallbackDetail and assigns it to the Callbacks field.
func (o *CallbackListResponse) SetCallbacks(v []CallbackDetail) {
	o.Callbacks = v
}

func (o CallbackListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallbackListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Callbacks) {
		toSerialize["callbacks"] = o.Callbacks
	}
	return toSerialize, nil
}

type NullableCallbackListResponse struct {
	value *CallbackListResponse
	isSet bool
}

func (v NullableCallbackListResponse) Get() *CallbackListResponse {
	return v.value
}

func (v *NullableCallbackListResponse) Set(val *CallbackListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCallbackListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCallbackListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallbackListResponse(val *CallbackListResponse) *NullableCallbackListResponse {
	return &NullableCallbackListResponse{value: val, isSet: true}
}

func (v NullableCallbackListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallbackListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


