/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

API version: 1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the Defense type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Defense{}

// Defense struct for Defense
type Defense struct {
	Id *string `json:"id,omitempty"`
	// Defense text
	Defense *string `json:"defense,omitempty"`
	// Defense status
	Status *string `json:"status,omitempty"`
	InfractionId *string `json:"infractionId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Files []DefenseFilesInner `json:"files,omitempty"`
}

// NewDefense instantiates a new Defense object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefense() *Defense {
	this := Defense{}
	return &this
}

// NewDefenseWithDefaults instantiates a new Defense object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefenseWithDefaults() *Defense {
	this := Defense{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Defense) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Defense) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Defense) SetId(v string) {
	o.Id = &v
}

// GetDefense returns the Defense field value if set, zero value otherwise.
func (o *Defense) GetDefense() string {
	if o == nil || IsNil(o.Defense) {
		var ret string
		return ret
	}
	return *o.Defense
}

// GetDefenseOk returns a tuple with the Defense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetDefenseOk() (*string, bool) {
	if o == nil || IsNil(o.Defense) {
		return nil, false
	}
	return o.Defense, true
}

// HasDefense returns a boolean if a field has been set.
func (o *Defense) HasDefense() bool {
	if o != nil && !IsNil(o.Defense) {
		return true
	}

	return false
}

// SetDefense gets a reference to the given string and assigns it to the Defense field.
func (o *Defense) SetDefense(v string) {
	o.Defense = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Defense) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Defense) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Defense) SetStatus(v string) {
	o.Status = &v
}

// GetInfractionId returns the InfractionId field value if set, zero value otherwise.
func (o *Defense) GetInfractionId() string {
	if o == nil || IsNil(o.InfractionId) {
		var ret string
		return ret
	}
	return *o.InfractionId
}

// GetInfractionIdOk returns a tuple with the InfractionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetInfractionIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfractionId) {
		return nil, false
	}
	return o.InfractionId, true
}

// HasInfractionId returns a boolean if a field has been set.
func (o *Defense) HasInfractionId() bool {
	if o != nil && !IsNil(o.InfractionId) {
		return true
	}

	return false
}

// SetInfractionId gets a reference to the given string and assigns it to the InfractionId field.
func (o *Defense) SetInfractionId(v string) {
	o.InfractionId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Defense) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Defense) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Defense) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Defense) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Defense) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Defense) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *Defense) GetFiles() []DefenseFilesInner {
	if o == nil || IsNil(o.Files) {
		var ret []DefenseFilesInner
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Defense) GetFilesOk() ([]DefenseFilesInner, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *Defense) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []DefenseFilesInner and assigns it to the Files field.
func (o *Defense) SetFiles(v []DefenseFilesInner) {
	o.Files = v
}

func (o Defense) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Defense) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Defense) {
		toSerialize["defense"] = o.Defense
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.InfractionId) {
		toSerialize["infractionId"] = o.InfractionId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableDefense struct {
	value *Defense
	isSet bool
}

func (v NullableDefense) Get() *Defense {
	return v.value
}

func (v *NullableDefense) Set(val *Defense) {
	v.value = val
	v.isSet = true
}

func (v NullableDefense) IsSet() bool {
	return v.isSet
}

func (v *NullableDefense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefense(val *Defense) *NullableDefense {
	return &NullableDefense{value: val, isSet: true}
}

func (v NullableDefense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


