/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

API version: 1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorDetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorDetailsInner{}

// ApiErrorDetailsInner struct for ApiErrorDetailsInner
type ApiErrorDetailsInner struct {
	Field string `json:"field"`
	Message string `json:"message"`
}

type _ApiErrorDetailsInner ApiErrorDetailsInner

// NewApiErrorDetailsInner instantiates a new ApiErrorDetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorDetailsInner(field string, message string) *ApiErrorDetailsInner {
	this := ApiErrorDetailsInner{}
	this.Field = field
	this.Message = message
	return &this
}

// NewApiErrorDetailsInnerWithDefaults instantiates a new ApiErrorDetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorDetailsInnerWithDefaults() *ApiErrorDetailsInner {
	this := ApiErrorDetailsInner{}
	return &this
}

// GetField returns the Field field value
func (o *ApiErrorDetailsInner) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetailsInner) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *ApiErrorDetailsInner) SetField(v string) {
	o.Field = v
}

// GetMessage returns the Message field value
func (o *ApiErrorDetailsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetailsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiErrorDetailsInner) SetMessage(v string) {
	o.Message = v
}

func (o ApiErrorDetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorDetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ApiErrorDetailsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorDetailsInner := _ApiErrorDetailsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorDetailsInner)

	if err != nil {
		return err
	}

	*o = ApiErrorDetailsInner(varApiErrorDetailsInner)

	return err
}

type NullableApiErrorDetailsInner struct {
	value *ApiErrorDetailsInner
	isSet bool
}

func (v NullableApiErrorDetailsInner) Get() *ApiErrorDetailsInner {
	return v.value
}

func (v *NullableApiErrorDetailsInner) Set(val *ApiErrorDetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorDetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorDetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorDetailsInner(val *ApiErrorDetailsInner) *NullableApiErrorDetailsInner {
	return &NullableApiErrorDetailsInner{value: val, isSet: true}
}

func (v NullableApiErrorDetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorDetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


