/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install @payzu/pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
)

// checks if the GetPixKey400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPixKey400Response{}

// GetPixKey400Response struct for GetPixKey400Response
type GetPixKey400Response struct {
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetPixKey400Response instantiates a new GetPixKey400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPixKey400Response() *GetPixKey400Response {
	this := GetPixKey400Response{}
	return &this
}

// NewGetPixKey400ResponseWithDefaults instantiates a new GetPixKey400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPixKey400ResponseWithDefaults() *GetPixKey400Response {
	this := GetPixKey400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetPixKey400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPixKey400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetPixKey400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetPixKey400Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetPixKey400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPixKey400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetPixKey400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetPixKey400Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetPixKey400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPixKey400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetPixKey400Response struct {
	value *GetPixKey400Response
	isSet bool
}

func (v NullableGetPixKey400Response) Get() *GetPixKey400Response {
	return v.value
}

func (v *NullableGetPixKey400Response) Set(val *GetPixKey400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPixKey400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPixKey400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPixKey400Response(val *GetPixKey400Response) *NullableGetPixKey400Response {
	return &NullableGetPixKey400Response{value: val, isSet: true}
}

func (v NullableGetPixKey400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPixKey400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


